import { getDb } from "../api/queries/connection";
import { languages, settings, partners, contents } from "./schema";

const LANGS = [
  { code: "ar", nameEn: "Arabic", nameNative: "العربية", dir: "rtl" as const, sortOrder: 1 },
  { code: "en", nameEn: "English", nameNative: "English", dir: "ltr" as const, sortOrder: 2 },
  { code: "ur", nameEn: "Urdu", nameNative: "اردو", dir: "rtl" as const, sortOrder: 3 },
  { code: "hi", nameEn: "Hindi", nameNative: "हिन्दी", dir: "ltr" as const, sortOrder: 4 },
  { code: "id", nameEn: "Indonesian", nameNative: "Bahasa Indonesia", dir: "ltr" as const, sortOrder: 5 },
  { code: "tl", nameEn: "Filipino", nameNative: "Filipino", dir: "ltr" as const, sortOrder: 6 },
];

const SETTINGS: Record<string, string> = {
  whatsapp_number: "966500000000",
  social_twitter: "",
  social_facebook: "",
  social_instagram: "",
  social_tiktok: "",
  chat_enabled: "true",
};

const PARTNERS = [
  { nameAr: "الجمعية — الجهة الحاضنة", nameEn: "The Association — Host Entity", sortOrder: 1 },
  { nameAr: "صنّاع الأثر — الشريك التشغيلي", nameEn: "Sunaa Al-Athar — Operating Partner", sortOrder: 2 },
  { nameAr: "قسط للمحاماة — الشريك القانوني", nameEn: "Qist Law — Legal Partner", sortOrder: 3 },
  { nameAr: "وزارة الموارد البشرية والتنمية الاجتماعية", nameEn: "Ministry of Human Resources and Social Development", logoUrl: "/assets/mhrsd.png", sortOrder: 4 },
];

/* ------------------------------------------------------------------ */
/* Site copy — written simply, addressed to the beneficiary.           */
/* ------------------------------------------------------------------ */
const C: Record<string, Record<string, string>> = {
  ar: {
    "brand.name": "حقوقك",
    "hero.badge": "مشروع اجتماعي • خدمة مجانية ١٠٠٪",
    "hero.title": "حقك أمانة… وإحنا جنبك",
    "hero.subtitle": "خدمة مجانية للعمال في السعودية. نسمعك بلغتك، نشرح لك حقوقك، ونساعدك توصل حقك — بسرية كاملة.",
    "hero.ctaWhatsapp": "كلمنا واتساب",
    "hero.ctaChat": "تحدث معنا الآن",
    "hero.ctaHelp": "اطلب مساعدة",
    "topics.title": "وش تحتاج مساعدة فيه؟",
    "topics.subtitle": "اختر مشكلتك، ونوصّلك بالحل خطوة بخطوة",
    "topic.salary": "راتبي متأخر",
    "topic.salary.desc": "ما استلمت راتبك أو مستحقاتك؟",
    "topic.contract": "مشكلة في العقد",
    "topic.contract.desc": "عقدك غير واضح أو مخالف للاتفاق؟",
    "topic.abuse": "معاملة سيئة",
    "topic.abuse.desc": "إساءة أو ضغط في العمل أو السكن؟",
    "topic.eosb": "مستحقات نهاية الخدمة",
    "topic.eosb.desc": "خلّصت شغلك وما أخذت حقك؟",
    "topic.rights": "أبي أفهم حقوقي",
    "topic.rights.desc": "شرح بسيط لحقوقك وواجباتك",
    "topic.other": "شيء آخر",
    "topic.other.desc": "أي مشكلة ثانية تواجهك",
    "steps.title": "كيف نساعدك؟",
    "steps.subtitle": "ثلاث خطوات بسيطة، ونمشي معك فيها كلها",
    "step1.title": "تواصل معنا",
    "step1.text": "كلمنا واتساب أو شات أو عبّ النموذج — باللغة اللي تريحك.",
    "step2.title": "نسمعك ونرشدك",
    "step2.text": "نستقبل حالتك بسرية تامة، ونشرح لك حقوقك والخطوات الصحيحة.",
    "step3.title": "نوصّل حقك",
    "step3.text": "نحاول نحلها وديًا. وإذا احتاجت محامي، نحوّلك للشريك القانوني ونتابع معك حتى تستلم حقك.",
    "services.title": "وش نقدّم لك؟",
    "service1.title": "توعية بلغتك",
    "service1.text": "محتوى سهل وبسيط يشرح حقوقك وواجباتك والمنصات الرسمية.",
    "service2.title": "استقبال حالتك",
    "service2.text": "نسمع مشكلتك، نجمع التفاصيل، ونرشدك للإجراء المناسب.",
    "service3.title": "تسوية ودية",
    "service3.text": "نحاول نحل المشكلة مع صاحب العمل بطريقة ودية وسريعة.",
    "service4.title": "إحالة قانونية",
    "service4.text": "إذا ما انحلّت وديًا، نحوّلك لمحامين متخصصين ونتابع معك.",
    "why.title": "ليش تختار «حقوقك»؟",
    "why1.title": "مجاني بالكامل",
    "why1.text": "ما نطلب منك أي مبلغ — اليوم ولا بكرة.",
    "why2.title": "بلغتك",
    "why2.text": "نخدمك بالعربية والإنجليزية والأردية والهندية والإندونيسية والفلبينية.",
    "why3.title": "سرية تامة",
    "why3.text": "معلوماتك محفوظة، وما نشاركها مع أحد بدون إذنك.",
    "why4.title": "معك حتى النهاية",
    "why4.text": "نمشي معك من أول رسالة حتى تستلم حقك كامل.",
    "about.title": "مشروع اجتماعي يخدم هذه الفئات",
    "about.text": "«حقوقك» مشروع اجتماعي غير ربحي يخدم العمالة الوافدة في السعودية — خصوصًا الفئات الأكثر حاجة: أصحاب الرواتب المتأخرة، والنزاعات العقدية، ومن يصعب عليهم فهم الإجراءات بسبب اللغة. نجمع لك التوعية والاستقبال والتسوية والإحالة القانونية في مسار واحد واضح.",
    "about.point": "خدمتنا الحقوقية للجميع، بدون أي شروط.",
    "partners.title": "شركاؤنا",
    "partners.subtitle": "نعمل مع جهات موثوقة عشان نوصل لك خدمة صح",
    "footer.about": "حقوقك — مشروع اجتماعي للتوعية بالحقوق العمالية ومساندة العمالة الوافدة في المملكة العربية السعودية.",
    "footer.contact": "تواصل معنا",
    "footer.follow": "تابعنا",
    "footer.rights": "جميع الحقوق محفوظة",
    "footer.free": "خدمة مجانية للجميع",
    "request.title": "اطلب مساعدة",
    "request.subtitle": "عبّ النموذج، وفريقنا يتواصل معك بأقرب وقت",
    "request.name": "اسمك",
    "request.phone": "رقم جوالك (اختياري)",
    "request.topic": "نوع المشكلة",
    "request.message": "اشرح لنا مشكلتك باختصار",
    "request.submit": "أرسل الطلب",
    "request.success": "وصلنا طلبك. بنتواصل معك بأقرب وقت، إن شاء الله.",
    "chat.title": "تحدث معنا",
    "chat.welcome": "هلا والله! اكتب سؤالك بلغتك، وبنرد عليك.",
    "chat.namePrompt": "وش نناديك؟",
    "chat.start": "ابدأ المحادثة",
    "chat.placeholder": "اكتب رسالتك هنا…",
    "chat.online": "متوفرون الآن",
    "chat.offline": "لسنا متوفرين الآن",
    "chat.offlineText": "فريقنا غير متوفر حاليًا. تقدر تكلمنا واتساب أو تترك طلب، وبنرد عليك بأقرب وقت.",
    "chat.waiting": "ثواني… نحوّلك لموظف متاح",
    "chat.agentJoined": "معك {name} من فريق حقوقك",
    "chat.ended": "انتهت المحادثة. تقدر تبدأ محادثة جديدة أي وقت.",
    "chat.you": "أنت",
    "nav.login": "دخول الموظفين",
    "lang.choose": "اختر لغتك",
  },
  en: {
    "brand.name": "Your Rights",
    "hero.badge": "A social project • 100% free service",
    "hero.title": "Your rights matter. We stand with you.",
    "hero.subtitle": "A free service for workers in Saudi Arabia. We listen in your language, explain your rights, and help you get them — fully private.",
    "hero.ctaWhatsapp": "Chat on WhatsApp",
    "hero.ctaChat": "Talk to us now",
    "hero.ctaHelp": "Ask for help",
    "topics.title": "What do you need help with?",
    "topics.subtitle": "Choose your problem — we guide you step by step.",
    "topic.salary": "My salary is late",
    "topic.salary.desc": "You didn't get your salary or dues?",
    "topic.contract": "Contract problem",
    "topic.contract.desc": "Your contract is unclear or broken?",
    "topic.abuse": "Bad treatment",
    "topic.abuse.desc": "Mistreatment at work or housing?",
    "topic.eosb": "End-of-service pay",
    "topic.eosb.desc": "Finished work but didn't get your rights?",
    "topic.rights": "I want to know my rights",
    "topic.rights.desc": "A simple guide to your rights and duties",
    "topic.other": "Something else",
    "topic.other.desc": "Any other problem you face",
    "steps.title": "How do we help you?",
    "steps.subtitle": "Three simple steps — we walk them with you.",
    "step1.title": "Contact us",
    "step1.text": "WhatsApp, chat, or the form — in the language you prefer.",
    "step2.title": "We listen and guide you",
    "step2.text": "We receive your case privately and explain your rights and the right steps.",
    "step3.title": "We get your rights back",
    "step3.text": "We try to solve it amicably. If it needs a lawyer, we refer you to our legal partner and follow up until you get your rights.",
    "services.title": "What do we offer you?",
    "service1.title": "Awareness in your language",
    "service1.text": "Simple content that explains your rights, duties, and official platforms.",
    "service2.title": "Case intake",
    "service2.text": "We hear your problem, collect the details, and guide you to the right action.",
    "service3.title": "Amicable settlement",
    "service3.text": "We try to solve the problem with the employer in a friendly, fast way.",
    "service4.title": "Legal referral",
    "service4.text": "If it can't be solved amicably, we refer you to specialized lawyers and follow up with you.",
    "why.title": "Why choose us?",
    "why1.title": "Completely free",
    "why1.text": "We never ask you for any money — ever.",
    "why2.title": "In your language",
    "why2.text": "We serve you in Arabic, English, Urdu, Hindi, Indonesian, and Filipino.",
    "why3.title": "Fully private",
    "why3.text": "Your information is safe. We never share it without your permission.",
    "why4.title": "With you to the end",
    "why4.text": "We walk with you from the first message until you get your full rights.",
    "about.title": "A social project serving these groups",
    "about.text": "Your Rights is a non-profit social project serving migrant workers in Saudi Arabia — especially the most vulnerable groups: workers with delayed salaries, contract disputes, and those who find official procedures hard because of language. We bring awareness, case intake, amicable settlement, and legal referral together in one clear path.",
    "about.point": "Our rights service is for everyone, with no conditions.",
    "partners.title": "Our partners",
    "partners.subtitle": "We work with trusted entities to serve you right.",
    "footer.about": "Your Rights — a social project for labor-rights awareness and support for migrant workers in the Kingdom of Saudi Arabia.",
    "footer.contact": "Contact us",
    "footer.follow": "Follow us",
    "footer.rights": "All rights reserved",
    "footer.free": "Free service for everyone",
    "request.title": "Ask for help",
    "request.subtitle": "Fill the form and our team will contact you soon.",
    "request.name": "Your name",
    "request.phone": "Your mobile number (optional)",
    "request.topic": "Problem type",
    "request.message": "Briefly explain your problem",
    "request.submit": "Send request",
    "request.success": "We received your request. We will contact you as soon as possible.",
    "chat.title": "Talk to us",
    "chat.welcome": "Hello! Write your question in your language and we will reply.",
    "chat.namePrompt": "What should we call you?",
    "chat.start": "Start chatting",
    "chat.placeholder": "Type your message here…",
    "chat.online": "We are online",
    "chat.offline": "We are not available now",
    "chat.offlineText": "Our team is currently unavailable. You can reach us on WhatsApp or leave a request, and we will reply soon.",
    "chat.waiting": "One moment… connecting you to an agent",
    "chat.agentJoined": "You are now with {name} from the Your Rights team",
    "chat.ended": "This conversation has ended. You can start a new one anytime.",
    "chat.you": "You",
    "nav.login": "Staff login",
    "lang.choose": "Choose your language",
  },
};
