// NOTE: this file's content is appended to db/seed.ts (see repo history).
// It is kept separate here only for readability of the translations.

export const ID_TL: Record<string, Record<string, string>> = {
  id: {
    "brand.name": "Hak Anda",
    "hero.badge": "Proyek sosial • Layanan 100% gratis",
    "hero.title": "Hak Anda, Tanggung Jawab Kami",
    "hero.subtitle": "Layanan gratis untuk pekerja di Arab Saudi. Kami mendengarkan dalam bahasa Anda, menjelaskan hak-hak Anda, dan membantu Anda mendapatkannya — sepenuhnya rahasia.",
    "hero.ctaWhatsapp": "Chat WhatsApp",
    "hero.ctaChat": "Bicara sekarang",
    "hero.ctaHelp": "Minta bantuan",
    "topics.title": "Apa yang Anda butuhkan?",
    "topics.subtitle": "Pilih masalah Anda — kami pandu langkah demi langkah.",
    "topic.salary": "Gaji saya terlambat",
    "topic.salary.desc": "Gaji atau hak Anda belum dibayar?",
    "topic.contract": "Masalah kontrak",
    "topic.contract.desc": "Kontrak tidak jelas atau dilanggar?",
    "topic.abuse": "Perlakuan buruk",
    "topic.abuse.desc": "Kekerasan di tempat kerja atau tempat tinggal?",
    "topic.eosb": "Pesangon akhir kerja",
    "topic.eosb.desc": "Selesai kerja tapi hak belum diterima?",
    "topic.rights": "Saya ingin tahu hak saya",
    "topic.rights.desc": "Panduan sederhana hak dan kewajiban Anda",
    "topic.other": "Lainnya",
    "topic.other.desc": "Masalah lain yang Anda hadapi",
    "steps.title": "Bagaimana kami membantu?",
    "steps.subtitle": "Tiga langkah mudah — kami menemani Anda.",
    "step1.title": "Hubungi kami",
    "step1.text": "WhatsApp, chat, atau formulir — dalam bahasa yang Anda sukai.",
    "step2.title": "Kami dengar dan pandu",
    "step2.text": "Kami menerima kasus Anda secara rahasia dan menjelaskan langkah yang benar.",
    "step3.title": "Kami perjuangkan hak Anda",
    "step3.text": "Kami coba selesaikan secara damai. Bila perlu pengacara, kami rujuk ke mitra hukum dan menemani sampai hak Anda diterima.",
    "services.title": "Apa yang kami berikan?",
    "service1.title": "Edukasi dalam bahasa Anda",
    "service1.text": "Konten sederhana tentang hak, kewajiban, dan platform resmi.",
    "service2.title": "Penerimaan kasus",
    "service2.text": "Kami mendengar masalah Anda, mengumpulkan detail, dan mengarahkan tindakan yang tepat.",
    "service3.title": "Penyelesaian damai",
    "service3.text": "Kami berusaha menyelesaikan masalah dengan majikan secara cepat dan bersahabat.",
    "service4.title": "Rujukan hukum",
    "service4.text": "Jika tidak selesai, kami rujuk ke pengacara ahli dan tetap mendampingi Anda.",
    "why.title": "Kenapa memilih kami?",
    "why1.title": "Sepenuhnya gratis",
    "why1.text": "Kami tidak pernah meminta uang — kapan pun.",
    "why2.title": "Dalam bahasa Anda",
    "why2.text": "Kami melayani dalam bahasa Arab, Inggris, Urdu, Hindi, Indonesia, dan Filipino.",
    "why3.title": "Sepenuhnya rahasia",
    "why3.text": "Informasi Anda aman. Kami tidak membagikannya tanpa izin Anda.",
    "why4.title": "Bersama sampai selesai",
    "why4.text": "Dari pesan pertama sampai hak Anda diterima penuh.",
    "about.title": "Proyek sosial untuk kelompok rentan",
    "about.text": "Hak Anda adalah proyek sosial nirlaba yang melayani pekerja migran di Arab Saudi — terutama kelompok paling rentan: korban gaji tertunda, sengketa kontrak, dan mereka yang kesulitan memahami prosedur karena bahasa. Kami menggabungkan edukasi, penerimaan kasus, penyelesaian damai, dan rujukan hukum dalam satu jalur yang jelas.",
    "about.point": "Layanan hukum kami untuk semua orang, tanpa syarat apa pun.",
    "partners.title": "Mitra kami",
    "partners.subtitle": "Kami bekerja dengan lembaga tepercaya untuk melayani Anda.",
    "footer.about": "Hak Anda — proyek sosial untuk edukasi hak ketenagakerjaan dan dukungan bagi pekerja migran di Kerajaan Arab Saudi.",
    "footer.contact": "Hubungi kami",
    "footer.follow": "Ikuti kami",
    "footer.rights": "Hak cipta dilindungi",
    "footer.free": "Layanan gratis untuk semua",
    "request.title": "Minta bantuan",
    "request.subtitle": "Isi formulir, tim kami akan segera menghubungi Anda.",
    "request.name": "Nama Anda",
    "request.phone": "Nomor HP (opsional)",
    "request.topic": "Jenis masalah",
    "request.message": "Jelaskan masalah Anda dengan singkat",
    "request.submit": "Kirim permintaan",
    "request.success": "Permintaan Anda kami terima. Kami akan segera menghubungi Anda.",
    "chat.title": "Bicara dengan kami",
    "chat.welcome": "Halo! Tulis pertanyaan Anda dalam bahasa Anda, kami akan menjawab.",
    "chat.namePrompt": "Siapa nama Anda?",
    "chat.start": "Mulai percakapan",
    "chat.placeholder": "Ketik pesan Anda di sini…",
    "chat.online": "Kami sedang online",
    "chat.offline": "Kami sedang tidak tersedia",
    "chat.offlineText": "Tim kami sedang tidak tersedia. Hubungi kami via WhatsApp atau tinggalkan permintaan, kami akan segera membalas.",
    "chat.waiting": "Sebentar… menghubungkan Anda ke petugas",
    "chat.agentJoined": "Anda sekarang bersama {name} dari tim Hak Anda",
    "chat.ended": "Percakapan selesai. Anda bisa memulai percakapan baru kapan saja.",
    "chat.you": "Anda",
    "nav.login": "Login staf",
    "lang.choose": "Pilih bahasa Anda",
  },
  tl: {
    "brand.name": "Ang Iyong Mga Karapatan",
    "hero.badge": "Proyektong panlipunan • 100% libreng serbisyo",
    "hero.title": "Ang Karapatan Mo, Pananagutan Namin",
    "hero.subtitle": "Libreng serbisyo para sa mga manggagawa sa Saudi Arabia. Nakikinig kami sa iyong wika, ipinapaliwanag ang iyong mga karapatan, at tumutulong na makuha mo ang mga ito — lubos na pribado.",
    "hero.ctaWhatsapp": "Chat sa WhatsApp",
    "hero.ctaChat": "Kausapin kami ngayon",
    "hero.ctaHelp": "Humingi ng tulong",
    "topics.title": "Ano ang kailangan mong tulong?",
    "topics.subtitle": "Piliin ang iyong problema — gagabayan ka namin nang hakbang-hakbang.",
    "topic.salary": "Delayed ang sahod ko",
    "topic.salary.desc": "Hindi pa natatanggap ang sahod o bayad mo?",
    "topic.contract": "Problema sa kontrata",
    "topic.contract.desc": "Hindi malinaw o nilalabag ang kontrata mo?",
    "topic.abuse": "Masamang pagtrato",
    "topic.abuse.desc": "Pang-aabuso sa trabaho o tirahan?",
    "topic.eosb": "End-of-service pay",
    "topic.eosb.desc": "Tapos na ang trabaho pero hindi nabayaran?",
    "topic.rights": "Gusto kong malaman ang mga karapatan ko",
    "topic.rights.desc": "Simpleng gabay sa iyong mga karapatan at tungkulin",
    "topic.other": "Iba pa",
    "topic.other.desc": "Ibang problema na hinaharap mo",
    "steps.title": "Paano ka namin tutulungan?",
    "steps.subtitle": "Tatlong simpleng hakbang — kasama mo kami.",
    "step1.title": "Makipag-ugnayan",
    "step1.text": "WhatsApp, chat, o form — sa wikang gusto mo.",
    "step2.title": "Dadalhin at gagabayan ka namin",
    "step2.text": "Tatanggapin namin ang iyong kaso nang pribado at ipapaliwanag ang tamang mga hakbang.",
    "step3.title": "Makukuha mo ang iyong karapatan",
    "step3.text": "Susubukan munang ayusin nang maayos. Kung kailangan ng abogado, irerefer ka namin sa legal partner at sasamahan ka hanggang makuha mo ang iyong karapatan.",
    "services.title": "Ano ang maibibigay namin sa iyo?",
    "service1.title": "Kaalaman sa iyong wika",
    "service1.text": "Simpleng nilalaman tungkol sa iyong mga karapatan, tungkulin, at opisyal na mga platform.",
    "service2.title": "Pagtanggap ng kaso",
    "service2.text": "Pakikinggan namin ang problema mo, kukunin ang mga detalye, at gagabayan ka sa tamang aksyon.",
    "service3.title": "Maayos na kasunduan",
    "service3.text": "Susubukan naming ayusin ang problema sa employer nang mabilis at maayos.",
    "service4.title": "Legal referral",
    "service4.text": "Kung hindi maayos, irerefer ka namin sa mga dalubhasang abogado at sasamahan ka.",
    "why.title": "Bakit kami ang pipiliin?",
    "why1.title": "Lubos na libre",
    "why1.text": "Hindi kami kailanman hihingi ng pera sa iyo.",
    "why2.title": "Sa iyong wika",
    "why2.text": "Nagse-serbisyo kami sa Arabic, English, Urdu, Hindi, Indonesian, at Filipino.",
    "why3.title": "Lubos na pribado",
    "why3.text": "Ligtas ang iyong impormasyon. Hindi namin ito ibabahagi nang walang pahintulot mo.",
    "why4.title": "Kasama hanggang dulo",
    "why4.text": "Mula sa unang mensahe hanggang makuha mo ang buong karapatan mo.",
    "about.title": "Proyektong panlipunan para sa mga grupong ito",
    "about.text": "Ang Your Rights ay isang non-profit na proyektong panlipunan para sa mga migranteng manggagawa sa Saudi Arabia — lalo na sa mga pinakamahina: mga may delayed na sahod, mga dispute sa kontrata, at mga nahihirapang intindihin ang mga proseso dahil sa wika. Pinagsasama namin ang kaalaman, pagtanggap ng kaso, maayos na kasunduan, at legal referral sa isang malinaw na landas.",
    "about.point": "Ang aming serbisyong legal ay para sa lahat, walang anumang kondisyon.",
    "partners.title": "Aming mga partner",
    "partners.subtitle": "Kami ay nakikipagtulungan sa mga mapagkakatiwalaang institusyon para magsilbi sa iyo.",
    "footer.about": "Your Rights — proyektong panlipunan para sa kaalaman sa mga karapatan ng manggagawa at suporta sa mga migranteng manggagawa sa Kaharian ng Saudi Arabia.",
    "footer.contact": "Makipag-ugnayan",
    "footer.follow": "I-follow kami",
    "footer.rights": "Nakalaan ang lahat ng karapatan",
    "footer.free": "Libreng serbisyo para sa lahat",
    "request.title": "Humingi ng tulong",
    "request.subtitle": "Punan ang form at makikipag-ugnayan ang aming team sa lalong madaling panahon.",
    "request.name": "Ang iyong pangalan",
    "request.phone": "Numero ng mobile (opsyonal)",
    "request.topic": "Uri ng problema",
    "request.message": "Ipaliwanag nang maikli ang iyong problema",
    "request.submit": "Ipadala ang kahilingan",
    "request.success": "Natanggap namin ang iyong kahilingan. Makikipag-ugnayan kami sa iyo sa lalong madaling panahon.",
    "chat.title": "Kausapin kami",
    "chat.welcome": "Kumusta! Isulat ang iyong tanong sa iyong wika at sasagutin ka namin.",
    "chat.namePrompt": "Ano ang itatawag namin sa iyo?",
    "chat.start": "Simulan ang usapan",
    "chat.placeholder": "I-type ang iyong mensahe dito…",
    "chat.online": "Online kami ngayon",
    "chat.offline": "Hindi kami available ngayon",
    "chat.offlineText": "Hindi available ang aming team ngayon. Maaari kang mag-WhatsApp o mag-iwan ng kahilingan, at sasagutin ka namin agad.",
    "chat.waiting": "Sandali lang… kinokonekta ka sa aming staff",
    "chat.agentJoined": "Kasama mo na ngayon si {name} mula sa Your Rights team",
    "chat.ended": "Natapos na ang usapan. Maaari kang magsimula ng bago anumang oras.",
    "chat.you": "Ikaw",
    "nav.login": "Staff login",
    "lang.choose": "Piliin ang iyong wika",
  },
};

export const AUDIENCE: Record<string, Record<string, string>> = {
  ar: {
    "audience.title": "من نخدم؟",
    "audience.1": "العمالة الوافدة غير الناطقة بالعربية",
    "audience.2": "أصحاب الرواتب والمستحقات المتأخرة",
    "audience.3": "أصحاب النزاعات العقدية",
    "audience.4": "من يصعب عليهم فهم الإجراءات بسبب اللغة",
  },
  en: {
    "audience.title": "Who we serve",
    "audience.1": "Migrant workers who don't speak Arabic",
    "audience.2": "Workers with delayed salaries and dues",
    "audience.3": "Workers in contract disputes",
    "audience.4": "Those who find procedures hard because of language",
  },
  ur: {
    "audience.title": "ہم کس کی خدمت کرتے ہیں؟",
    "audience.1": "غیر عربی بولنے والے مہاجر مزدور",
    "audience.2": "روکی ہوئی تنخواہ اور مستحقات والے مزدور",
    "audience.3": "معاہدے کے تنازعات میں مبتلا مزدور",
    "audience.4": "جن کے لیے زبان کی وجہ سے طریقہ کار مشکل ہے",
  },
  hi: {
    "audience.title": "हम किसकी सेवा करते हैं?",
    "audience.1": "गैर-अरबी बोलने वाले प्रवासी मज़दूर",
    "audience.2": "रुकी सैलरी और बकाया राशि वाले मज़दूर",
    "audience.3": "कॉन्ट्रैक्ट विवादों में फंसे मज़दूर",
    "audience.4": "जिन्हें भाषा की वजह से प्रक्रियाएँ कठिन लगती हैं",
  },
  id: {
    "audience.title": "Siapa yang kami layani",
    "audience.1": "Pekerja migran yang tidak berbahasa Arab",
    "audience.2": "Pekerja dengan gaji dan hak yang tertunda",
    "audience.3": "Pekerja dengan sengketa kontrak",
    "audience.4": "Mereka yang kesulitan memahami prosedur karena bahasa",
  },
  tl: {
    "audience.title": "Sino ang aming pinagsisilbihan",
    "audience.1": "Migranteng manggagawa na hindi nagsasalita ng Arabic",
    "audience.2": "Mga may delayed na sahod at benepisyo",
    "audience.3": "Mga may dispute sa kontrata",
    "audience.4": "Mga nahihirapang intindihin ang mga proseso dahil sa wika",
  },
};
